---
# Ansible configuration
# User configuration
ansible_user: k8sadmin
ansible_ssh_private_key_file: ~/.ssh/k8s_ansible_key
ansible_become: true
ansible_become_method: sudo

# Network configuration
control_plane_gateway: 10.8.16.1  # UDM-Pro interface is the gateway
admin_gateway: 10.8.16.1  # UDM-Pro interface is the gateway
pod_network_subnet: "10.8.28.0/23"
pod_subnet_mask: "/23"       # 10.8.28.0/23
service_subnet: "10.8.38.0"
service_subnet_mask: "/24"   # 10.8.38.0/24
control_plane_endpoint: "{{ k8s_api_vip }}:{{ k8s_ha_port }}"  # Use VIP for HA control plane
k8s_api_vip: "10.8.18.2"  # virtual IP for HA setup
k8s_api_port: 6443 # virtual IP for HA setup
k8s_ha_port: 16443 # virtual IP for HA setup
mgmt_subnet: "10.8.16.0"
mgmt_subnet_mask: "/24"      # 10.8.16.0/24
control_pane_subnet: "10.8.18.0"
control_subnet_mask: "/24"   # 10.8.18.0/24

# Kubernetes configuration
kubernetes_version: "v1.33.0"
cni_plugin: "cilium"
cilium_version: "1.17.3"
containerd_version: "2.0.0"
etcd_version: "3.5.9"

# Load balancer network
loadbalancer_cidr: "/27"
loadbalancer_subnet: "10.8.58.0"




# Storage network
storage_subnet: "10.8.48.0"
storage_subnet_mask: "/24"   # 10.8.48.0/24
enable_jumbo_frames: true
storage_mtu: 9000


