---
all:
  children:
      children:
        control_plane_nodes:
          hosts:
            raspberry_pis:
              k8s-cp-01:
                ansible_host: 10.8.18.86
              k8s-cp-02:
                ansible_host: 10.8.18.87
              k8s-cp-03:
                ansible_host: 10.8.18.88
        worker_nodes:
          hosts:
            ms-01s:
              k8s-ms01-node-01:
                ansible_host: 10.8.18.90
              k8s-ms01-node-02:
                ansible_host: 10.8.18.91
        admin_nodes:
          hosts:
            raspberry_pis:
             k8s-admin:
                ansible_host: 10.8.16.85
                ansible_connection: local  # Use local connection when running on this host
                ansible_become: true  # Add thi
                ansible_become_user: root 
                control_plane_ip: 10.8.18.85
                k8s_role: admin
          
