---
all:
  children:
    raspberry_pis:
      vars:
        ansible_user: k8sadmin
        ansible_ssh_private_key_file: ~/.ssh/k8s_ansible_key
      children:
        control_plane_nodes:
          hosts:
            k8s-cp-01:
              ansible_host: 10.8.18.86
            k8s-cp-02:
              ansible_host: 10.8.18.87
            k8s-cp-03:
              ansible_host: 10.8.18.88
        admin_nodes:
          hosts:
            k8s-admin:
              ansible_host: 10.8.16.85
              ansible_connection: local  # Use local connection when running on this host
              ansible_become_user: k8sadmin
              control_plane_ip: 10.8.18.85
              k8s_role: admin
