---
all:
  children:
    k8s_cluster:  # Changed from k8s-cluster
      children:
        control_plane_nodes:  # Changed from control-plane-nodes
          hosts:
            k8s-cp-01:
              ansible_host: 10.8.18.86
            k8s-cp-02:
              ansible_host: 10.8.18.87
            k8s-cp-03:
              ansible_host: 10.8.18.88
        worker_nodes:  # Changed from worker-nodes
          hosts:
            k8s-ms01-node-01:
              ansible_host: 10.8.16.90
              mgmt_ip: 10.8.16.90/24
              second_if_ip: 10.8.18.90/24
              vlan_configs:
                - id: 28
                  link: bond0
                  addresses:
                    - 10.8.28.90/23
                - id: 38
                  link: bond0
                  addresses:
                    - 10.8.38.90/24
                - id: 48
                  link: bond0
                  addresses:
                    - 10.8.48.90/24
            k8s-ms01-node-02:
              ansible_host: 10.8.16.91
              mgmt_ip: 10.8.16.91/24
              second_if_ip: 10.8.18.91/24
              vlan_configs:
                - id: 28
                  link: bond0
                  addresses:
                    - 10.8.28.91/23
                - id: 38
                  link: bond0
                  addresses:
                    - 10.8.38.91/24
                - id: 48
                  link: bond0
                  addresses:
                    - 10.8.48.91/24

    admin_nodes:  # Changed from admin-nodes
      hosts:
        k8s-admin:
          ansible_host: 10.8.16.85
          ansible_connection: local  # Use local connection when running on this host
          ansible_become: true  # Enable privilege escalation for this host
          ansible_become_user: root
          k8s_role: admin
    raspberry_pis:  # Changed from raspberry-pis
      hosts:
        k8s-admin:
        k8s-cp-01:
        k8s-cp-02:
        k8s-cp-03:
    ms_01s:  # Changed from ms-01s
      hosts:
        k8s-ms01-node-01:
          vpro_ip: 10.8.16.190
        k8s-ms01-node-02:
          vpro_ip: 10.8.16.191