---
all:
  children:
    raspberry_pis:
      vars:
        ansible_user: jason
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      children:
        control_plane_nodes:
          hosts:
            k8s-cp-01:
              ansible_host: 10.8.16.86
            k8s-cp-02:
              ansible_host: 10.8.16.87
            k8s-cp-03:
              ansible_host: 10.8.16.88
        admin_nodes:
          hosts:
            k8s-admin:
              ansible_host: 10.8.16.85  
