---
- name: Ping Test
  hosts: raspberry_pis
  gather_facts: yes  # Changed to yes to demonstrate fact gathering
  
  tasks:
    - name: Ping all hosts
      ping:
      
    - name: Get hostname
      command: hostname
      register: hostname_output
      changed_when: false
      
    - name: Display hostname
      debug:
        msg: "Host {{ inventory_hostname }} reports hostname: {{ hostname_output.stdout }}"
        
    - name: Display some system facts
      debug:
        msg: |
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Architecture: {{ ansible_architecture }}
          Memory: {{ ansible_memtotal_mb }} MB
          IP Address: {{ ansible_default_ipv4.address }}
