---
- name: Test SSH connectivity with agent
  hosts: all
  gather_facts: yes
  
  tasks:
    - name: Get hostname
      command: hostname
      register: hostname_output
      changed_when: false
      
    - name: Display hostname
      debug:
        msg: "Successfully connected to {{ hostname_output.stdout }}"
        
    - name: Show OS information
      debug:
        msg: "Running {{ ansible_distribution }} {{ ansible_distribution_version }}"
