---
# configure_admin_networking.yml
- name: Configure basic networking for Kubernetes admin nodes
  hosts: admin_nodes
  become: true
  gather_facts: true

  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
      
    - name: Update /etc/hosts with node's own entry
      lineinfile:
        path: /etc/hosts
        line: "127.0.1.1 {{ inventory_hostname }}"
        regexp: "^127.0.1.1"
        state: present
      
    - name: Create netplan configuration for admin networking
      copy:
        dest: /etc/netplan/60-k8s-network.yaml
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              eth0:
                dhcp4: no
                addresses:
                  - {{ hostvars[inventory_hostname]['ansible_host'] }}/24  # Control plane IP
                routes:
                  - to: default
                    via: {{ admin_gateway }}
                nameservers:
                  addresses: [{{ admin_gateway }}, 1.1.1.1, 1.0.0.1]  # UDM-Pro first, then Cloudflare
        mode: '0644'
      register: netplan_config
      
    - name: Add control plane hosts to /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          # Gateways
          {{ control_plane_gateway }} control-pane-gateway
          {{ admin_gateway }} admin-network-gateway
          
          # Control plane nodes
          10.8.18.86 k8s-cp-01
          10.8.18.87 k8s-cp-02
          10.8.18.88 k8s-cp-03
          
          # Worker nodes
          10.8.18.90 k8s-ms01-node-01
          10.8.18.91 k8s-ms01-node-02
          10.8.16.90 k8s-ms01-node-01-mgmt
          10.8.16.91 k8s-ms01-node-02-mgmt
          
          # Admin node
          10.8.16.85 k8s-admin
          
          # Virtual IP for HA control plane
          {{ k8s_api_vip }} k8s-apiserver
        marker: "# {mark} KUBERNETES NODES"
        state: present
      
    - name: Check netplan syntax
      command: netplan generate
      register: netplan_generate
      changed_when: false
      failed_when: netplan_generate.rc != 0
      when: netplan_config.changed

    - name: Apply netplan configuration if syntax is valid
      command: netplan apply
      when: netplan_config.changed and netplan_generate.rc == 0

    - name: Wait for network to stabilize
      wait_for_connection:
        delay: 5
        timeout: 60
      when: netplan_config.changed and netplan_generate.rc == 0
      
    - name: Show effective IP configuration
      command: ip addr show eth0
      register: ip_config
      changed_when: false
      
    - name: Display IP configuration
      debug:
        msg: "{{ ip_config.stdout_lines }}"
      
    - name: Test DNS resolution
      command: nslookup cloudflare.com
      register: dns_test
      changed_when: false
      failed_when: false
      
    - name: Display DNS test results
      debug:
        msg: "{{ dns_test.stdout_lines }}"