---
# install_k8s_prerequisites.yml
- name: Install Kubernetes prerequisites
  hosts: control_plane_nodes  # This targets only the control plane nodes, not the admin
  become: true
  gather_facts: true
  
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
        update_cache: yes
      
    - name: Disable swap - temporarily
      command: swapoff -a
      changed_when: true
      
    - name: Disable swap - permanently
      replace:
        path: /etc/fstab
        regexp: '^([^#].*\sswap\s+sw\s+.*)$'
        replace: '# \1'
      register: swap_disabled
      
    - name: Create modules configuration for Kubernetes
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        mode: '0644'
      register: modules_configured
      
    - name: Load overlay module
      modprobe:
        name: overlay
        state: present
      
    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present
      
    - name: Create sysctl configuration for Kubernetes networking
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
        mode: '0644'
      register: sysctl_configured
      
    - name: Apply sysctl configuration
      command: sysctl --system
      when: sysctl_configured.changed
      
    - name: Verify modules are loaded
      shell: lsmod | grep -e br_netfilter -e overlay
      register: module_check
      changed_when: false
      failed_when: false
      
    - name: Show module status
      debug:
        msg: "Kernel modules loaded: {{ module_check.rc == 0 }}"